### PR TITLE
Fix GC return error of generic calls

### LINKED ISSUE #155: GC error
```julia
using Enzyme

Enzyme.API.printall!(true)

t = 0.0

function tobedifferentiated(cond, a)::Float64
    if cond
        t + t
    else
        0.0
    end
end

autodiff(tobedifferentiated, true, Active(2.1))
```

### PR DESCRIPTION
**Pull request by wsmoses**
Resolves #155

Requires https://github.com/wsmoses/Enzyme/pull/383 (and jll bump)

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -448,6 +448,30 @@ end
...
+			a + t
+		else
+			0.0
+		end
+	end
+
+	@test 1.0 ≈ autodiff(tobedifferentiated2, true, Active(2.1))[1]
+end
+
+@testset "Return GC error" begin
```
Comment (vchuravy) [inline test/runtests.jl:474]: Is this the right name for the test below?
