### PR TITLE
Handle closures

### LINKED ISSUE #62: Enzyme crash for simple user struct type
this crash on both master and latest release

```julia
julia> using Enzyme

julia> using Enzyme

julia> struct Foo
           x::Float64
       end

julia> function (f::Foo)(x::Float64)
           return f.x + x
       end

julia> Enzyme.pullback(Foo(1.0), 2.0)(1.0)
julia: /workspace/srcdir/Enzyme/enzyme/Enzyme/CApi.cpp:253: LLVMOpaqueValue* EnzymeCreatePrimalAndGradient(EnzymeLogicRef, LLVMValueRef, CDIFFE_TYPE, CDIFFE_TYPE*, size_t, EnzymeTypeAnalysisRef, uint8_t, uint8_t, uint8_t, LLVMTypeRef, CFnTypeInfo, uint8_t*, size_t, EnzymeAugmentedReturnPtr, uint8_t, uint8_t): Assertion `argnum < uncacheable_args_size' failed.

signal (6): Aborted
in expression starting at REPL[5]:1
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f557877f728)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
EnzymeCreatePrimalAndGradient at /workspace/srcdir/Enzyme/enzyme/Enzyme/CApi.cpp:253
EnzymeCreatePrimalAndGradient at /home/roger/.julia/packages/Enzyme/A97If/src/api.jl:83
enzyme! at /home/roger/.julia/packages/Enzyme/A97If/src/compiler.jl:249
unknown function (ip: 0x7f551575c205)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#codegen#30 at /home/roger/.julia/packages/Enzyme/A97If/src/compiler.jl:435
codegen##kw at /home/roger/.julia/packages/Enzyme/A97If/src/compiler.jl:386 [inlined]
_thunk at /home/roger/.julia/packages/Enzyme/A97If/src/compiler.jl:761
unknown function (ip: 0x7f5515cc51f1)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
callback at /home/roger/.julia/packages/Enzyme/A97If/src/compiler.jl:822
unknown function (ip: 0x7f5515cbe801)
_ZN12_GLOBAL__N_134CompileCallbackMaterializationUnit11materializeEN4llvm3orc29MaterializationResponsibilityE at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession26materializeOnCurrentThreadESt10unique_ptrINS0_19MaterializationUnitESt14default_deleteIS3_EENS0_29MaterializationResponsibilityE at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZNSt17_Function_handlerIFvSt10unique_ptrIN4llvm3orc19MaterializationUnitESt14default_deleteIS3_EENS2_29MaterializationResponsibilityEEPS8_E9_M_invokeERKSt9_Any_dataOS6_OS7_ at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession17runOutstandingMUsEv at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupENS0_10LookupKindERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS8_EENS0_15SymbolLookupSetENS0_11SymbolStateENS_15unique_functionIFvNS_8ExpectedINS_8DenseMapINS0_15SymbolStringPtrENS_18JITEvaluatedSymbolENS_12DenseMapInfoISI_EENS_6detail12DenseMapPairISI_SJ_EEEEEEEEESt8functionIFvRKNSH_IS6_NS_8DenseSetISI_SL_EENSK_IS6_EENSN_IS6_SV_EEEEEE at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS7_EERKNS0_15SymbolLookupSetENS0_10LookupKindENS0_11SymbolStateESt8functionIFvRKNS_8DenseMapIS5_NS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoISK_EEEENSL_IS5_EENS_6detail12DenseMapPairIS5_SN_EEEEEE at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm3orc16ExecutionSession6lookupERKSt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS7_EENS0_15SymbolStringPtrENS0_11SymbolStateE at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm3orc25JITCompileCallbackManager22executeCompileCallbackEm at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm6detail18UniqueFunctionBaseIvJmNS_15unique_functionIKFvmEEEEE8CallImplIKZNS_3orc30LocalJITCompileCallbackManagerINS7_14OrcX86_64_SysVEEC4ERNS7_16ExecutionSessionEmRNS_5ErrorEEUlmS4_E_EEvPvmRS4_ at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
_ZN4llvm3orc19LocalTrampolinePoolINS0_14OrcX86_64_SysVEE7reenterEPvS4_ at /home/roger/packages/julias/julia-1.6/bin/../lib/julia/libLLVM-11jl.so (unknown line)
unknown function (ip: 0x7f5578976043)
unknown function (ip: 0x7f5578975ff5)
#12 at /home/roger/.julia/packages/Enzyme/A97If/src/Enzyme.jl:151
unknown function (ip: 0x7f5515cbc787)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:115
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:204
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:155 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:562
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:670
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:877
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:825
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:929
eval at ./boot.jl:360 [inlined]
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
#run_repl#42 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:317
run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:305
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#874 at ./client.jl:387
jfptr_YY.874_41532.clone_1 at /home/roger/packages/julias/julia-1.6/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:714
#invokelatest#2 at ./essentials.jl:708 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
run_main_repl at ./client.jl:372
exec_options at ./client.jl:302
_start at ./client.jl:485
jfptr__start_34289.clone_1 at /home/roger/packages/julias/julia-1.6/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
true_main at /buildworker/worker/package_linux64/build/src/jlapi.c:560
repl_entrypoint at /buildworker/worker/package_linux64/build/src/jlapi.c:702
main at julia (unknown line)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4007d8)
Allocations: 33613790 (Pool: 33600323; Big: 13467); GC: 45
[1]    9172 abort (core dumped)  julia --project
```

### PR DESCRIPTION
**Pull request by wsmoses**
Fixes #62

### CODE REVIEW

File: src/compiler.jl [hunk 1]
```diff
@@ -469,17 +480,18 @@ end
 
 ##
 # Thunk
-## 
+##
 
 struct CombinedAdjointThunk{f, RT, TT}
+    Fn::f
```
Comment (vchuravy) [inline src/compiler.jl:486]: Julia convention is capitalization the other way around `fn::F`

File: src/compiler.jl [hunk 2]
```diff
@@ -469,17 +480,18 @@ end
...
     # primal::Ptr{Cvoid}
     adjoint::Ptr{Cvoid}
 end
 
 @inline (thunk::CombinedAdjointThunk{F, RT, TT})(args...) where {F, RT, TT} =
-   enzyme_call(thunk.adjoint, TT, RT, args...)
+   enzyme_call(thunk.adjoint, thunk.Fn, TT, RT, args...)
 
-@generated function enzyme_call(f::Ptr{Cvoid}, tt::Type{T}, rt::Type{RT}, args::Vararg{Any, N}) where {T, RT, N}
+@generated function enzyme_call(f::Ptr{Cvoid}, F::FTy, tt::Type{T}, rt::Type{RT}, args::Vararg{Any, N}) where {FTy, T, RT, N}
```
Comment (vchuravy) [inline src/compiler.jl:494]:
```suggestion
@generated function enzyme_call(ptr::Ptr{Cvoid}, f::F, tt::Type{T}, rt::Type{RT}, args::Vararg{Any, N}) where {F, T, RT, N}
```

File: test/abi.jl [hunk 3]
```diff
@@ -93,3 +93,38 @@ using Test
...
     # returns: sret, const/ghost, !deserve_retbox
 end
+
+
+@testset "Callable ABI" begin
+    function method(f, x)
+        return f(x)
+    end
+
+    struct AFoo
```
Comment (vchuravy) [inline test/abi.jl:103]: Remains to test:
- `mutable struct`
- `Duplicated` on struct
