### PR TITLE
Restore symbol location if replaced

### LINKED ISSUE #74: Symbol lookup failure
(@wsmoses not sure whether to report this here or at [Enzyme](https://github.com/wsmoses/Enzyme) itself)

```julia
using Enzyme

a = 2
c = 3

f(a, c) = a * √c
∂f_∂a = autodiff(f, Active(a), c)
```

results in 

```
name = "__memmove_ssse3_back"
ERROR: Enzyme: Symbol lookup failed. Aborting!
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] resolver(name::Cstring, ctx::Ptr{Nothing})
    @ Enzyme.Compiler /user/.julia/dev/Enzyme/src/compiler.jl:826
```

Doesn't happen when using `c` instead of `√c`.

Tested using Enzyme.jl v0.6.0 with official Julia Linux x86_64 binaries, system info:

```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

### PR DESCRIPTION
**Pull request by wsmoses**
Resolves #74

### CODE REVIEW

File: test/runtests.jl [hunk 1]
```diff
@@ -206,6 +206,13 @@ end
     @test fd ≈ ForwardDiff.derivative(foo, x)
     @test fd ≈ Zygote.gradient(foo, x)[1]
     @test fd ≈ first(autodiff(foo, Active(x)))
+
+    a = 2
+    c = 3
+
+    f(a, c) = a * √c
```
Comment (vchuravy) [inline test/runtests.jl:213]: Try naming this something no `f`
